### ISSUE TITLE
Anotações

### ISSUE THREAD

**Issue by danfma** [rcosta87/app-front#1]
- Tome cuidado ao fazer inscrever componentes em serviços que retornem observables. Alguns observables não retornam somente um valor, mantendo a inscrição ativa, então você causaria um memory leak na sua aplicação por excesso de inscrições em um observable;
- Mantenha o padrão, alguns dos seus componentes estão em português e a maioria em inglês;
- Evite chamar métodos na view do angular. Métodos não podem ser observados, causando dirty checking na aplicação e degradando o desempenho;
- A organização do seu sistema ficaria um pouco melhor se tivesse organizado a estrutura por features ao invés de por componentes;
- Sem testes;

- Seus componentes estão bem simples e quase sem lógica! Muito bom!!

- Erro: somente quando usando o yarn:
![image](https://user-images.githubusercontent.com/101121/55290741-501c7280-53ad-11e9-9cb0-310d862f6895.png)

**Comment by rcosta87** [comment]
Olá Prof. Daniel, gostaria de agradecer o feedback. Fiz o refactoring da aplicação, seguindo as suas sugestões.
